# This is a basic workflow to help you get started with Actions

name: CI-MAVEN

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: staging_environment


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v2
        with:
         java-version: '11'
         distribution: 'adopt'
         architecture: x64

      # Runs a set of commands using the runners shell
      - name: maven build
        run: mvn clean package
      
      - uses: actions/upload-artifact@v2
        with: 
          path: target
          name: drop
          
      - name: publish package
        run: mvn --batch-mode deploy
        
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          


